#!/bin/bash

if [ -x /opt/nvim-linux-x86_64/bin/nvim ] ;  then
	echo "ok"
	exit 0
fi
# lets attempt to install it
wget https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
sudo rm -rf /opt/nvim*
sudo tar -C /opt -xzf nvim-linux-x86_64.tar.gz
echo "changed"
